spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${db.name}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:ewm_user}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:ewm_password}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema-${spring.application.name}.sql
      continue-on-error: false