server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/stats/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
