server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/stats/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/**

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
