spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: comment_service_route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/admin/comments/{commentId}/**,/users/{userId}/comments/**,/events/{eventId}/comments/**,/comments/{commentId}/**

        - id: request_service_route
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests/**,/users/{userId}/requests/**

        - id: event_service_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/admin/events/**,/users/{userId}/events/**,/events/**

        - id: user_service_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/admin/users/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
