spring:
  application:
    name: gateway-server
  config:
    import: "configserver:http://config-server:8888"
  main:
    web-application-type: reactive
  cloud:
    config:
      discovery:
        enabled: false
      fail-fast: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
