server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/{commentId}/**,/users/{userId}/comments/**,/events/{eventId}/comments/**,/comments/{commentId}/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests/**,/users/{userId}/requests/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/admin/events/**,/users/{userId}/events/**,/events/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true