spring:
  application:
    name: event-service
server:
  port: 8080
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
