spring:
  application:
    name: event-service
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      discovery:
        enabled: false
      fail-fast: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
