server:
  port: 0

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE

spring:
  application:
    name: event-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewm-db
    username: ewm
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  jackson:
    mapper:
      allow-coercion-of-scalars: true
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss

hibernate:
  jdbc:
    time_zone: UTC

logbook:
  format:
    style: http

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/